# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66ile2.proto\"*\n\tNumTensor\x12\x1d\n\tmy_arrays\x18\x01 \x03(\x0b\x32\n.NumMatrix\"+\n\tNumMatrix\x12\x1e\n\rmy_sub_arrays\x18\x01 \x03(\x0b\x32\x07.NumRow\"\x1e\n\x06NumRow\x12\x14\n\x08my_array\x18\x01 \x03(\x05\x42\x02\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUMROW.fields_by_name['my_array']._options = None
  _NUMROW.fields_by_name['my_array']._serialized_options = b'\020\001'
  _NUMTENSOR._serialized_start=15
  _NUMTENSOR._serialized_end=57
  _NUMMATRIX._serialized_start=59
  _NUMMATRIX._serialized_end=102
  _NUMROW._serialized_start=104
  _NUMROW._serialized_end=134
# @@protoc_insertion_point(module_scope)
