# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tensors.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/tensors.proto\x12\x05proto\"0\n\tNumTensor\x12#\n\tmy_arrays\x18\x01 \x03(\x0b\x32\x10.proto.NumMatrix\"1\n\tNumMatrix\x12$\n\rmy_sub_arrays\x18\x01 \x03(\x0b\x32\r.proto.NumRow\"\x1e\n\x06NumRow\x12\x14\n\x08my_array\x18\x01 \x03(\x05\x42\x02\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.tensors_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUMROW.fields_by_name['my_array']._options = None
  _NUMROW.fields_by_name['my_array']._serialized_options = b'\020\001'
  _NUMTENSOR._serialized_start=30
  _NUMTENSOR._serialized_end=78
  _NUMMATRIX._serialized_start=80
  _NUMMATRIX._serialized_end=129
  _NUMROW._serialized_start=131
  _NUMROW._serialized_end=161
# @@protoc_insertion_point(module_scope)
